@startuml
left to right direction
title 画面遷移図

state ホーム_未ログイン
state ログイン
state アカウント登録
state 検索結果一覧
state 解説登録
state 特定の言葉のページ{
  state "解説及びコメント表示" as 解説表示
  state コメント登録
  
  解説表示 -[hidden]-> コメント登録
}

[*] --> ホーム_未ログイン
ホーム --> 解説表示 : サジェスト
ホーム -right-> 検索結果一覧 :検索
ホーム -down-> 解説登録
ホーム -> アカウント登録
ホーム -> ログイン
ホーム <- ログイン : 成功
ログイン -down> アカウント登録

検索結果一覧 -> 解説登録
ログイン <-- 解説登録
検索結果一覧 --> 解説表示
解説登録 --> 解説表示 : 登録

解説表示 --> コメント登録 : 登録
解説表示 <-- コメント登録 : 登録成功


@enduml