@startuml
left to right direction
title 画面遷移図

state ホーム
state ログイン
state アカウント登録
state 検索結果一覧
state 解説登録
state 特定の言葉のページ{
  state "解説及びコメント表示" as 解説表示
  state コメント登録
  
  解説表示 -[hidden]-> コメント登録
}

[*] --> ホーム

ホーム --> 解説表示 :解説サジェスト
ホーム --> 検索結果一覧 :検索
ホーム --> 解説登録
ホーム --> アカウント登録
ホーム --> ログイン

ホーム <-- ログイン :ログイン成功
ホーム <-- アカウント登録 : 登録成功

解説登録 -> ログイン :未ログインなら
ログイン -> アカウント登録


検索結果一覧 -> 解説登録
検索結果一覧 --> 解説表示
解説登録 --> 解説表示 : 登録

解説表示 --> コメント登録 : 登録
解説表示 <-- コメント登録 : 登録成功

ログイン <-up-- コメント登録 : 未ログインなら


@enduml